#!/bin/bash

# Remove Orphaned Packages
function orphaned {
	show_info 'Removing orphaned packages...'
	show_warning 'Requires root privileges'
	sudo apt autoremove -y
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Orphaned packages have been successfully removed." 8 78
	cleanup
}

# Remove Leftover Config files
function leftovers {
	show_info 'Removing leftover configuration files...'
	show_warning 'Requires root privileges'
	sudo dpkg --purge $(COLUMNS=200 dpkg -l | grep '^rc' | tr -s ' ' | cut -d ' ' -f 2)
	show_success 'Done.'
	# Check
	whiptail --title "Finished" --msgbox "Leftover configuration files have been removed." 8 78
	cleanup
}

# Clean apt cache
function clean-cache {
	show_info 'Cleaning package cache...'
	show_warning 'Requires root privileges'
	sudo apt clean
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Package cache has been cleaned." 8 78
	cleanup
}

# Cleanup System
function cleanup {
	eval `resize` 
	CLEANUP=$(whiptail \
		--notags \
		--title "System Cleanup" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		clean-cache	'Clean package cache' \
		leftovers	'Remove leftover configuration files' \
		orphaned	'Remove orphaned packages' \
		3>&1 1>&2 2>&3)
	 
	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		$CLEANUP
	else
		main
	fi
}