#!/bin/bash

# Perform Raspberry Pi firmware upgrade
function upgrade {
	if (whiptail --title "Raspberry Pi Firmware Upgrade" --yesno "It is recommended that you reboot your Raspberry Pi after the firmware upgrade. \n\nAre you sure you want proceed?" 10 60) then
		# Upgrade firmware
		show_info 'Upgrading firmware...'
		show_warning 'Requires root privileges'
		sudo rpi-update
		show_success 'Done.'
		if (whiptail --title "Firmware upgrade complete" --yesno "A reboot is needed to activate the new firmware. Reboot now?" 10 60) then
			# Reboot
			show_info 'Rebooting...'
			show_warning 'Requires root privileges'
		 	sudo reboot
		else
			whiptail --title "Firmware upgrade complete." --msgbox "No? Alright, but reboot is still recommended." 8 78
			main
		fi
	else
		main
	fi
}