#!/bin/bash

# Perform Raspberry Pi firmware upgrade
function upgrade {
	if (whiptail --title "Raspberry Pi Firmware Upgrade" --yesno "Proceed with system update?" 10 60) then
		# Update repository information
		show_info 'Updating firmware...'
		show_warning 'Requires root privileges'
		sudo rpi-update
		show_success 'Done.'
		# Check
		EXITSTATUS=$1
		if [[ $EXITSTATUS != 0 ]]; then
			# Already up-to-date
			show_success 'Already up-to-date.'
			whiptail --title "Finished" --msgbox "Firmware is up-to-date." 8 78
			main
		else
			whiptail --title "Finished" --msgbox "Firmware update complete" 8 78
			main
		fi
	else
		main
	fi
}